### ISSUE TITLE
Cell color and styling

### ISSUE THREAD

**Issue by omaramen99** [LuisEnMarroquin/json-as-xlsx#68] opened 2023-01-11 08:33 UTC
the package is awesome, I'm just wondering if I can set some styling to the cells

**Comment by elyse0** [comment] 2023-01-11 08:55
No, styling it's not supported because it's a paid feature in SheetJs 

Duplicate of https://github.com/LuisEnMarroquin/json-as-xlsx/issues/46

**Closed** 2023-04-18 20:30 UTC
