### ISSUE TITLE
Empty content

### ISSUE THREAD

**Issue by chaizeg** [LuisEnMarroquin/json-as-xlsx#23] opened 2021-11-16 14:28 UTC
Hello, I'm using this library with Vue, and I have a backend that could return a potentially empty array, in which case I keep getting this error:
`"TypeError: Reduce of empty array with no initial value"`

II'm not sure if that's already possible but think It would be great if this library can return in case of an empty array, instead of an error, an empty file with the indicated columns

**Comment by elyse0** [comment] 2021-11-18 00:19
Yeah, the problem is iterated over content to create 'jsonSheetRows', but because content was empty, the map returned an empty array. 

The error comes from the library 'xlsx' because we were passing that empty array to **utils.json_to_sheet()** 🐞 

It's fixed with #24 😄 

https://github.com/LuisEnMarroquin/json-as-xlsx/blob/bbc93716abee8ccc6b22768d1da828f95b4bf46e/index.ts#L61-L70

**Comment by LuisEnMarroquin** [comment] 2021-11-22 03:22
Hi there, it should be fixed on #2fab9ea3aa2f7d392fd34a3e37cf4495dde26c69, thanks to @elyse0 🤗

Feel free to reopen is anything is wrong

**Closed by LuisEnMarroquin** 2021-11-22 03:22 UTC
